"""add street in addresses

Revision ID: 14fa6911077e
Revises: d9d37e2cd1b8
Create Date: 2024-01-01 16:20:00.190232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14fa6911077e'
down_revision: Union[str, None] = 'd9d37e2cd1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('street', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'street')
    # ### end Alembic commands ###
