"""add index in addresses

Revision ID: d9d37e2cd1b8
Revises: a03a2fc00734
Create Date: 2024-01-01 16:17:36.381823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d37e2cd1b8'
down_revision: Union[str, None] = 'a03a2fc00734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('index', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'index')
    # ### end Alembic commands ###
